/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nickwar_MainActivity */

#ifndef _Included_cn_nickwar_MainActivity
#define _Included_cn_nickwar_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nickwar_MainActivity
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_nickwar_MainActivity_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     cn_nickwar_MainActivity
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_nickwar_MainActivity_setJNIEnv
  (JNIEnv *, jobject);

/*
 * Class:     cn_nickwar_MainActivity
 * Method:    stop_rtp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_nickwar_MainActivity_stop_1rtp
  (JNIEnv *, jobject);

/*
 * Class:     cn_nickwar_MainActivity
 * Method:    exit_rtp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_nickwar_MainActivity_exit_1rtp
  (JNIEnv *, jobject);

/*
 * Class:     cn_nickwar_MainActivity
 * Method:    nativeWorker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_nickwar_MainActivity_nativeWorker
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
